### ISSUE TITLE
Can't change category names in supplier_parameters.yaml

### ISSUE THREAD

**Issue by Fivefold** [sparkmicro/Ki-nTree#195]
According to documentation the `supplier_parameters.yaml` follows this structure:

```yaml
CATEGORY_NAME:
  INVENTREE_PARAMETER_NAME:
    - SUPPLIER_1_PARAMETER_NAME_1
    - SUPPLIER_1_PARAMETER_NAME_2
    - SUPPLIER_2_PARAMETER_NAME_1
```

I use a custom `categories.yaml`, here is part of it:

```yaml
CATEGORIES:
  Active Components:
    Integrated Circuits:
      Voltage Regulators: null
```

Now in `supplier_parameters.yaml` I tried to change line 202 in the following code block from `Power Management` to `Voltage Regulators`: https://github.com/sparkmicro/Ki-nTree/blob/7f894dd5f1d89bce128e022bcd39fa7fb603d890/kintree/config/inventree/supplier_parameters.yaml#L202-L208

As soon as I start Ki-nTree or try to create a part, this line gets changed back to `Power Management`, even though I have _no_ Power Management category in InvenTree or `categories.yaml`.

I can change supplier parameters or add InvenTree parameters in `supplier_parameters.yaml` just fine, but I can't seem to change the category names.

Am I doing something wrong?
