### ISSUE TITLE
Categories map for other supplier like TME.

### ISSUE THREAD

**Issue by NightSkySK** [sparkmicro/Ki-nTree#214]
I would like to contribute to the project to help build categories and parametric mapping for other suppliers than Digikey.
I've started with TME categories mapping. Can someone help to confirm if I'm going in the right direction with this mapping:

here is the sample of capacitor mapping in `tme_categories.yaml`

```yaml
Capacitors:
  Aluminium:
  - Electrolytic capacitors
  - SMD electrolytic capacitors
  - THT electrolytic capacitors
  - SNAP-IN electrolytic capacitors
  Ceramic:
  - MLCC capacitors
  - MLCC SMD capacitors
  - MLCC THT capacitors
  - MLCC array capacitors
  - Ceramic capacitors
  - THT ceramic capacitors
  Polymer:
  - Polymer and Hybrid Capacitors
  - SMD Polymer Capacitors
  - THT Polymer Capacitors
  - SMD Hybrid Capacitors
  - THT Hybrid Capacitors
  - Polymer - tantalum capacitors
  Super Capacitors:
  - Supercapacitors
  Tantalum:
  - Tantalum capacitors
  - SMD tantalum capacitors
  - THT tantalum capacitors
```

so let's take as example https://www.tme.eu/pl/en/details/0805b104k500ct/mlcc-smd-capacitors/walsin/
it belong to the category:
[Passives](https://www.tme.eu/pl/en/katalog/passives_112309/)/[Capacitors](https://www.tme.eu/pl/en/katalog/capacitors_26/)/[MLCC capacitors](https://www.tme.eu/pl/en/katalog/mlcc-capacitors_100560/)/[MLCC SMD capacitors](https://www.tme.eu/pl/en/katalog/mlcc-smd-capacitors_113537/)

Is it correctly mapped in the above yaml file?

As I checked the source code `kintree/database/inventree_interface.py` method is `get_categories_from_supplier_data` is currently fixed to check only digikey categories mapping:
`category_map = config_interface.load_supplier_categories_inversed(supplier_config_path=settings.CONFIG_DIGIKEY_CATEGORIES)`

so to make it work with some other supplier categories mapping there need to be made some more changes here, isn't it?
